const PRIMARY_COLOR = '#3498DB';
const PRIMARY_COLOR_HIGHT = '#2980B9';
const PRIMARY_COLOR_LIGHT = '#9FD9FF';

const SECONDARY_COLOR = 'rgba(56, 39, 180, 0.08)';
const SECONDARY_COLOR_HIGHT = 'rgba(163, 162, 172, 0.61)';
const SECONDARY_COLOR_LIGHT = '#fff';

const ALERT_COLOR = '#E74C3C';

const TEXT_PRIMARY_COLOR = '#3E3E3E';
const TEXT_SECONDARY_COLOR = 'rgba(163, 162, 172, 0.71)';

const TRANSPARENT = 'rgba(0, 0, 0, 0.4)';

export {
    PRIMARY_COLOR,
    PRIMARY_COLOR_HIGHT,
    PRIMARY_COLOR_LIGHT,
    SECONDARY_COLOR,
    SECONDARY_COLOR_HIGHT,
    SECONDARY_COLOR_LIGHT,
    ALERT_COLOR,
    TRANSPARENT,
    TEXT_PRIMARY_COLOR,
    TEXT_SECONDARY_COLOR
}